### ISSUE TITLE
Hiding the entire page initially via CSS is not accesible

### ISSUE THREAD

**Issue by kidonng** [notion-enhancer/notion-enhancer.github.io#4]
The entire page has `.hidden` class on it which is removed when the page finishes loading _JavaScript_:

https://github.com/notion-enhancer/notion-enhancer.github.io/blob/7667e8f32de3aa175846ff9af86830d990cd0886/_layouts/base.njk#L3

The problem is:

- JavaScript may fail, or even be disabled.
- The page stays invisible even after most things are loaded

Would you like to explain the reason to do this? Could we get rid of it?

**Comment by dragonwocky** [comment]
It was done to prevent a flash of unthemed content on load prior to the correct theme (dark/light) being applied to the page. It's more important for the page to work, though, so I'll remove that.
